// ==UserScript==
// @name         Last.fm Inject Spotify Buttons
// @namespace    https://github.com/
// @version      3.13
// @description  Replace Last.fm track, album and artist play buttons with Spotify-style buttons and actions
// @match        https://www.last.fm/*
// @grant        GM_openInTab
// ==/UserScript==

// AUTO-GENERATED from src/lastfm-inject/. Do not edit this file directly.
// Edit the module files under src/lastfm-inject/ and re-run scripts/build.sh.

(function () {
    'use strict';

    const LOG_PREFIX = "[lastfm→spotify]";

    const log = (...args)=>
        console.log(LOG_PREFIX, ...args);


    log("script loaded");



    // ---------- config bridge ----------

    // When running as the Chrome extension, content/bridge.js populates
    // window.__LFS_CONFIG from chrome.storage and keeps it in sync. Under
    // Tampermonkey there is no bridge, so getConfig() falls back to the
    // defaults below and behaviour matches the stand-alone userscript.

    const CONFIG_DEFAULTS = {
        defaultAction:    "play",
        menuDelay:        280,
        entityBadges:     false,
        queueLimit:       10,
    };

    function getConfig(){
        const bridged =
            (typeof window !== "undefined" && window.__LFS_CONFIG) || null;
        return bridged
            ? Object.assign({}, CONFIG_DEFAULTS, bridged)
            : CONFIG_DEFAULTS;
    }




    // ---------- styles ----------

    // Icon and overlay-button sizes are driven by a single --lfs-size
    // CSS custom property. Every per-container rule below just sets
    // that variable (and any custom position); the shared button rules
    // read it via var(--lfs-size, 32px). This means adding a new host
    // is one small block, not four repeated width/height selectors.

    const style = document.createElement("style");

    style.textContent = `

/* Inner icon (SVG wrapper) shared across every button we inject. */
.spotify-custom-button {
    display:flex !important;
    align-items:center !important;
    justify-content:center !important;
    width:var(--lfs-size, 32px) !important;
    height:var(--lfs-size, 32px) !important;
    opacity:.8;
    transition:transform .12s ease, opacity .12s ease;
}
.spotify-custom-button svg {
    display:block !important;
    width:var(--lfs-size, 32px) !important;
    height:var(--lfs-size, 32px) !important;
}
[data-spotify-replaced]:hover .spotify-custom-button { opacity:1; }


/* Neutralize Last.fm's own ::before/::after play-glyph pseudo-elements
   on any playlink we've taken over, and center our icon inside
   whatever container Last.fm gave us. */
a[data-spotify-replaced]::before,
a[data-spotify-replaced]::after,
button[data-spotify-replaced]::before,
button[data-spotify-replaced]::after { display:none !important; }

a[data-spotify-replaced],
button[data-spotify-replaced] {
    display:inline-flex !important;
    align-items:center !important;
    justify-content:center !important;
}


/* Album/track cover-art play buttons (.desktop-playlink). Force a
   centered 60x60 overlay on the cover cell and grow the inner icon
   to fill it. Excludes:
     - .recs-feed-playlink       (home recs feed — smaller 44px)
     - .image-overlay-playlink-link (chart thumbnails — native 32px fits)
     - .header-new-playlink      (album header pill — album pages
                                  carry BOTH classes, so exclude it
                                  here or the pill gets flipped into a
                                  60x60 absolute-positioned overlay) */
.desktop-playlink[data-spotify-replaced]:not(.recs-feed-playlink):not(.image-overlay-playlink-link):not(.header-new-playlink) {
    position:absolute !important;
    top:50% !important;
    left:50% !important;
    transform:translate(-50%, -50%) !important;
    margin:0 !important;
    width:60px !important;
    height:60px !important;
    --lfs-size:56px;
}
.recs-feed-playlink { --lfs-size:44px; }


/* Artist-page header "Play artist" button — keep native pill layout
   and text, just swap the inline play triangle for a small Spotify
   disc. Last.fm reserves left padding on the pill for its own inline
   triangle background; we override it so our icon isn't pushed to
   the right of the pill's left edge. */
.header-new-playlink[data-spotify-replaced] {
    display:inline-flex !important;
    align-items:center !important;
    padding-left:14px !important;
    white-space:nowrap !important;
    --lfs-size:22px;
}
.header-new-playlink .spotify-custom-button { margin-right:8px; }


/* Shared style for buttons we inject from scratch (artist-avatar
   overlays and the featured-artist top-right corner). Individual
   host rules below set position + --lfs-size. */
.spotify-similar-artist-button,
.spotify-featured-artist-button {
    position:absolute !important;
    z-index:3 !important;
    background:transparent !important;
    border:0 !important;
    padding:0 !important;
    cursor:pointer !important;
    filter:drop-shadow(0 2px 6px rgba(0,0,0,.55));
}
.spotify-similar-artist-button { bottom:6px !important; right:6px !important; }


/* Per-host positioning containers + sizes. Each of these:
     - marks the host position:relative so our absolute button anchors
       correctly,
     - sets --lfs-size for the inner icon. */
.catalogue-overview-similar-artists-item-image,
.artist-similar-artists-sidebar-item-image,
.music-more-artists-item-image,
.artist-featured-items-item-image { position:relative !important; }

.catalogue-overview-similar-artists-item-image { --lfs-size:44px; }
.artist-similar-artists-sidebar-item-image     { --lfs-size:28px; }
.music-more-artists-item-image                 { --lfs-size:44px; }
.artist-featured-items-item-image              { --lfs-size:36px; }

/* Small square cover thumbnails inside big featured-artist cards
   ("Latest Release", "Popular this week"). Center the button on the
   cover instead of the default bottom-right corner. */
.artist-featured-items-item-image .spotify-similar-artist-button {
    top:calc(50% - 18px) !important;
    left:calc(50% - 18px) !important;
    right:auto !important;
    bottom:auto !important;
}

.music-recommended-artists-artist-avatar {
    position:relative !important;
    display:block !important;
    --lfs-size:48px;
}


/* Chart Top-Artists rows have small round avatars with no native
   play button. Scope .avatar to the chart image cell so we don't
   grab avatars elsewhere. Center the button (via calc offsets, not
   transform, so it composes with the hover-scale inline transform). */
.globalchart-image .avatar,
.weeklychart-image .avatar {
    position:relative !important;
    display:inline-block !important;
    --lfs-size:26px;
}
.globalchart-image .avatar .spotify-similar-artist-button,
.weeklychart-image .avatar .spotify-similar-artist-button {
    top:calc(50% - 13px) !important;
    left:calc(50% - 13px) !important;
    right:auto !important;
    bottom:auto !important;
}


/* /home/artists (and /music/+recommended/artists) recs-feed cards.
   Anchor at the wrap so we sit above the title/description overlay
   layer; pin top-left with a high z-index so clicks aren't swallowed
   by the overlay. */
.recs-feed-cover-image-wrap {
    position:relative !important;
    --lfs-size:44px;
}
.recs-feed-cover-image-wrap > .spotify-similar-artist-button {
    top:8px !important;
    left:8px !important;
    right:auto !important;
    bottom:auto !important;
    z-index:20 !important;
}


/* Big featured-artist cards on /music ("Artists for you", "Hot right
   now"). No native play button, so overlay one in the top-right. */
.music-featured-item.music-featured-artist {
    position:relative !important;
    --lfs-size:52px;
}
.spotify-featured-artist-button {
    top:14px !important;
    right:14px !important;
    filter:drop-shadow(0 2px 8px rgba(0,0,0,.6));
}


/* New Releases grid on /music. Many rows ship without Last.fm's own
   .music-releases-item-playlink (rows that instead have .js-link-block
   on their inner div); overlay a centered button on the cover for
   those. Rows that DO have a native playlink are already swapped by
   replaceStationButtons and picked up by the shared .desktop-playlink
   rule higher up, so we don't touch them here.

   Also hide the injected button until the card is hovered, to match
   Last.fm's own show-on-hover behaviour for the native playlink
   variant (otherwise our injected rows look busier than the swapped
   ones in the same grid). */
.music-releases-item-image {
    position:relative !important;
    --lfs-size:56px;
}
.music-releases-item-image .spotify-similar-artist-button {
    top:calc(50% - 28px) !important;
    left:calc(50% - 28px) !important;
    right:auto !important;
    bottom:auto !important;
    opacity:0;
    transition:opacity .12s ease;
}
.music-releases-item-wrap:hover .music-releases-item-image .spotify-similar-artist-button {
    opacity:1;
}


/* Album-page tracklist — the empty .chartlist-play cells get a
   compact inline Spotify button. Setting --lfs-size on the cell
   applies to both our injected button and native
   .chartlist-play-button playlinks that replaceTrackButtons swapped.
   The second rule strips Last.fm's per-element sizing/padding/
   background-image so both variants render as identical
   28x28 transparent hosts around our SVG. */
.chartlist-play {
    --lfs-size:28px;
}
.chartlist-play [data-spotify-replaced] {
    width:var(--lfs-size, 28px) !important;
    height:var(--lfs-size, 28px) !important;
    padding:0 !important;
    margin:0 !important;
    min-width:0 !important;
    line-height:1 !important;
    background:transparent !important;
    background-image:none !important;
    border:0 !important;
    text-decoration:none !important;
    color:inherit !important;
}
.spotify-chartlist-play-button {
    display:inline-flex !important;
    align-items:center !important;
    cursor:pointer !important;
}


/* Album-page header — injected alongside Bookmark/More in the pill
   action row. Sized to sit comfortably next to the native pills. */
.spotify-album-header-button {
    display:inline-flex !important;
    align-items:center !important;
    background:transparent !important;
    border:0 !important;
    padding:0 !important;
    margin-right:8px !important;
    cursor:pointer !important;
    --lfs-size:40px;
    filter:drop-shadow(0 2px 6px rgba(0,0,0,.4));
}


/* Hover menu (single shared element attached to <body>). */
.spotify-menu {
    position:fixed;
    display:none;
    min-width:132px;
    padding:4px;
    background:rgba(40,40,40,.78);
    backdrop-filter:blur(18px) saturate(160%);
    -webkit-backdrop-filter:blur(18px) saturate(160%);
    border:1px solid rgba(255,255,255,.12);
    border-radius:8px;
    box-shadow:
        0 10px 30px rgba(0,0,0,.4),
        0 2px 6px rgba(0,0,0,.25);
    z-index:2147483647 !important;
    font-family:-apple-system, BlinkMacSystemFont, "Segoe UI", Arial, sans-serif;
    font-size:13px;
    font-weight:500;
    letter-spacing:.1px;
    color:#eee;
    pointer-events:auto;
    opacity:0;
    transform:translateX(-4px);
    transition:opacity .12s ease, transform .12s ease;
}
.spotify-menu.spotify-menu--shown {
    opacity:1;
    transform:translateX(0);
}
.spotify-menu-item {
    display:flex;
    align-items:center;
    gap:10px;
    padding:7px 10px;
    border-radius:4px;
    cursor:pointer;
    white-space:nowrap;
    user-select:none;
    transition:background .1s ease, color .1s ease;
}
.spotify-menu-item svg {
    width:14px;
    height:14px;
    flex-shrink:0;
    fill:currentColor;
    opacity:.9;
}
.spotify-menu-item:hover {
    background:rgba(29,185,84,.16);
    color:#1DB954;
}


/* Hide Last.fm's "Play all" button in the Similar Artists section
   header — its station URL is just the current artist, so it
   duplicates the main PLAY ARTIST button. */
section:has(> ol.catalogue-overview-similar-artists) .section-controls .inline-section-control {
    display:none !important;
}


/* Global hamburger menu injected right after .masthead-logo. Present
   on every Last.fm page.

   The parent .masthead-inner-wrap is display:flex with
   justify-content:space-between — two children (logo and nav
   cluster). Dropping a third item in the middle would spread them
   equally, so we use margin-right:auto to break the space-between
   layout: our wrap stays flush against the logo, and everything
   after it gets pushed to the right edge as before. */
.spotify-nav-menu-wrap {
    position:relative !important;
    display:inline-flex !important;
    align-items:center !important;
    margin-left:14px !important;
    margin-right:auto !important;
    vertical-align:middle !important;
}

/* The toggle button — 3-line icon stacked in the extension's
   red / white / green identity colours so it reads as "the Spotify
   ↔ Last.fm bridge" rather than a stock nav hamburger. Transparent
   by default; a subtle red→green gradient wash appears on hover. */
.spotify-nav-menu-toggle {
    display:inline-flex !important;
    align-items:center !important;
    justify-content:center !important;
    width:48px !important;
    height:48px !important;
    background:transparent !important;
    border:0 !important;
    padding:0 !important;
    margin:0 !important;
    border-radius:10px !important;
    cursor:pointer !important;
    transition:background .15s ease, transform .12s ease;
}
.spotify-nav-menu-toggle:hover,
.spotify-nav-menu-toggle[aria-expanded="true"] {
    background:linear-gradient(
        135deg,
        rgba(213, 16, 7, 0.22) 0%,
        rgba(29, 185, 84, 0.22) 100%
    ) !important;
}
.spotify-nav-menu-toggle:active {
    transform:scale(0.94);
}
.spotify-nav-menu-toggle svg {
    width:36px !important;
    height:36px !important;
    display:block !important;
}

/* One-shot attention pulse when the toggle first mounts on a page,
   so users notice the button exists. Removed by JS after the
   animation completes so hover/expanded states aren't fighting it. */
@keyframes spotify-nav-toggle-pulse {
    0%, 100% {
        background:transparent;
        transform:scale(1);
        box-shadow:0 0 0 0 rgba(29,185,84,0);
    }
    50% {
        background:linear-gradient(
            135deg,
            rgba(213, 16, 7, 0.55) 0%,
            rgba(29, 185, 84, 0.55) 100%
        );
        transform:scale(1.12);
        box-shadow:0 0 0 6px rgba(29,185,84,.15);
    }
}
.spotify-nav-menu-toggle--pulse {
    animation:spotify-nav-toggle-pulse 1.1s ease-in-out 2;
}

/* Dropdown panel. Shares the frosted-dark aesthetic with the
   existing per-button .spotify-menu so both feel like the same
   product surface. */
.spotify-nav-menu {
    position:absolute !important;
    top:calc(100% + 6px) !important;
    left:0 !important;
    min-width:240px !important;
    padding:6px !important;
    background:rgba(30,30,30,.92) !important;
    backdrop-filter:blur(18px) saturate(160%);
    -webkit-backdrop-filter:blur(18px) saturate(160%);
    border:1px solid rgba(255,255,255,.12) !important;
    border-radius:10px !important;
    box-shadow:
        0 12px 32px rgba(0,0,0,.5),
        0 2px 6px rgba(0,0,0,.3);
    z-index:2147483646 !important;
    font-family:-apple-system, BlinkMacSystemFont, "Segoe UI", Arial, sans-serif !important;
    font-size:13px !important;
    color:#eee !important;
    opacity:0;
    transform:translateY(-4px);
    pointer-events:none;
    transition:opacity .12s ease, transform .12s ease;
}
.spotify-nav-menu[data-open="true"] {
    opacity:1;
    transform:translateY(0);
    pointer-events:auto;
}

/* Menu items — buttons and anchors share styling. */
.spotify-nav-menu-item {
    display:flex !important;
    align-items:center !important;
    gap:12px !important;
    width:100% !important;
    padding:9px 12px !important;
    background:transparent !important;
    border:0 !important;
    border-radius:6px !important;
    cursor:pointer !important;
    color:#eee !important;
    font:inherit !important;
    font-weight:500 !important;
    text-align:left !important;
    text-decoration:none !important;
    white-space:nowrap !important;
    transition:background .1s ease, color .1s ease;
}
.spotify-nav-menu-item:hover,
.spotify-nav-menu-item:focus-visible {
    background:rgba(29,185,84,.16) !important;
    color:#1DB954 !important;
    outline:0 !important;
}
.spotify-nav-menu-item[disabled],
.spotify-nav-menu-item[aria-disabled="true"] {
    opacity:.55 !important;
    cursor:default !important;
    background:transparent !important;
    color:#eee !important;
}
.spotify-nav-menu-icon {
    display:inline-flex !important;
    align-items:center !important;
    justify-content:center !important;
    width:20px !important;
    height:20px !important;
    flex-shrink:0 !important;
    color:currentColor !important;
}
.spotify-nav-menu-icon svg {
    width:20px !important;
    height:20px !important;
    display:block !important;
    fill:currentColor !important;
}
.spotify-nav-menu-divider {
    height:1px !important;
    margin:4px 6px !important;
    background:rgba(255,255,255,.1) !important;
}

/* Inline status line under an item (e.g. "Loading recommendations…"). */
.spotify-nav-menu-status {
    padding:2px 12px 8px 44px !important;
    color:#aaa !important;
    font-size:12px !important;
    font-style:italic !important;
}


/* Small pill buttons injected next to a user profile's section
   headers ("Recent Tracks", "Top Tracks"). Sits inline with the
   <h2>; sized down so it doesn't dominate the header. Fetches
   whatever URL the header's anchor points at, respecting any
   time-range filter Last.fm is currently showing. */
.spotify-user-queue-pill {
    margin-left:12px !important;
    vertical-align:middle !important;
}
.spotify-user-queue-button {
    display:inline-flex !important;
    align-items:center !important;
    gap:6px !important;
    background:#1DB954 !important;
    border:0 !important;
    padding:3px 10px 3px 4px !important;
    margin:0 !important;
    border-radius:999px !important;
    cursor:pointer !important;
    color:#fff !important;
    font-family:inherit !important;
    font-weight:700 !important;
    font-size:10px !important;
    line-height:1 !important;
    letter-spacing:.8px !important;
    text-transform:uppercase !important;
    white-space:nowrap !important;
    transition:background .12s ease, transform .12s ease;
}
.spotify-user-queue-button:hover {
    background:#25e46b !important;
    transform:scale(1.04);
}
.spotify-user-queue-button[aria-disabled="true"],
.spotify-user-queue-button[disabled] {
    opacity:.65 !important;
    cursor:default !important;
    transform:none !important;
}
.spotify-user-queue-icon {
    display:inline-flex !important;
    align-items:center !important;
    justify-content:center !important;
    width:18px !important;
    height:18px !important;
    background:rgba(0,0,0,.22) !important;
    border-radius:50% !important;
    flex-shrink:0 !important;
}
.spotify-user-queue-icon svg {
    width:12px !important;
    height:12px !important;
    display:block !important;
    fill:currentColor !important;
}

`;

    document.head.appendChild(style);




    // ---------- icon ----------

    // Every icon shares the green Spotify disc. Play and like also
    // overlay the three wave lines from the Spotify wordmark; queue
    // drops them because horizontal wave strokes would clash visually
    // with the horizontal queue-list bars.

    const SPOTIFY_DISC = `
<circle
    cx="16"
    cy="16"
    r="16"
    fill="#1DB954"/>`;

    const SPOTIFY_WAVES = `
<path
    d="M8 12.5C14 10.5 21 11 25 13"
    fill="none"
    stroke="#000"
    stroke-width="2"
    stroke-linecap="round"/>

<path
    d="M9 16C14 14.5 20 15 23.5 17"
    fill="none"
    stroke="#000"
    stroke-width="2"
    stroke-linecap="round"/>

<path
    d="M10.5 19.5C14 18.5 18 19 21 20.5"
    fill="none"
    stroke="#000"
    stroke-width="2"
    stroke-linecap="round"/>`;

    const SPOTIFY_GLYPHS = {

        play: `${SPOTIFY_WAVES}
<path
    d="M13 9L13 23L23 16Z"
    fill="#fff"/>`,

        queue: `
<g transform="translate(4 4) scale(0.75)">
<path
    d="M9 11.5h14M9 16h14M9 20.5h9"
    fill="none"
    stroke="#fff"
    stroke-width="2.4"
    stroke-linecap="round"/>
</g>`,

        like: `${SPOTIFY_WAVES}
<g transform="translate(4 4) scale(0.75)">
<path
    d="M16 24c-6.2-4.5-9.5-7.4-9.5-11.6 0-2.7 2-4.8 4.7-4.8 1.8 0 3.5 1 4.8 2.7 1.3-1.7 3-2.7 4.8-2.7 2.7 0 4.7 2.1 4.7 4.8 0 4.2-3.3 7.1-9.5 11.6z"
    fill="#fff"/>
</g>`,

    };

    // Optional entity badge in the bottom-right of the disc. Rendered
    // only when the popup's "Show entity badges" toggle is on. Each
    // badge is a small white circle background with a dark icon inside
    // (person / record / musical note) sized to sit at (24, 24) with
    // radius 5 in the 32x32 viewBox.

    const SPOTIFY_ENTITY_BADGES = {

        artist: `
<circle cx="24" cy="24" r="5" fill="#fff"/>
<circle cx="24" cy="22.3" r="1.3" fill="#111"/>
<path d="M20.6 27c0-1.8 1.6-2.9 3.4-2.9s3.4 1.1 3.4 2.9z" fill="#111"/>`,

        album: `
<circle cx="24" cy="24" r="5" fill="#fff"/>
<circle cx="24" cy="24" r="3" fill="#111"/>
<circle cx="24" cy="24" r="0.7" fill="#fff"/>`,

        track: `
<circle cx="24" cy="24" r="5" fill="#fff"/>
<ellipse cx="22.8" cy="26" rx="1.3" ry="1" fill="#111"/>
<path d="M23.9 26v-4.6" stroke="#111" stroke-width="0.7" stroke-linecap="round"/>
<path d="M23.9 21.4c1.5.3 1.9 1.6 1.1 2.5" stroke="#111" stroke-width="0.7" fill="none" stroke-linecap="round"/>`,

    };

    function spotifyIcon(action, entity){

        const glyph = SPOTIFY_GLYPHS[action] || SPOTIFY_GLYPHS.play;

        const badge = (getConfig().entityBadges && entity)
            ? (SPOTIFY_ENTITY_BADGES[entity] || "")
            : "";

        // Badge sits at (24, 24) in the raw glyph coordinates; wrap it
        // in a translate(3 3) so it renders at (27, 27) — half over the
        // green disc, half poking out into the bottom-right corner for
        // a clearer "attached" look.
        const badgeMarkup = badge
            ? `<g transform="translate(3 3)">${badge}</g>`
            : "";

        return `
<svg viewBox="0 0 32 32"
     xmlns="http://www.w3.org/2000/svg"
     aria-hidden="true">${SPOTIFY_DISC}${glyph}${badgeMarkup}
</svg>`;

    }




    // ---------- Spotify tab launch ----------

    function openSpotify(url){

        GM_openInTab(
            url,
            {
                active:false,
                insert:true,
                setParent:true
            }
        );

    }



    function makeSpotifyUrl(entity, artist, name, action){

        const query =
            name
                ? `${artist} ${name}`
                : artist;


        // We deliberately land on the generic /search/{q} page rather
        // than the typed /search/{q}/tracks|albums|artists pages. Typed
        // pages use different DOM shapes (e.g. tracklist-row on /tracks)
        // and Spotify changes them independently. The generic page has
        // one stable list-row layout for all entity types, and the
        // puppeteer disambiguates using the `entity` param below.

        return (
            "https://open.spotify.com/search/" +
            encodeURIComponent(query) +
            "?lastfm=true" +
            "&entity=" + entity +
            "&action=" + action
        );

    }


    // Batch dispatch: build a single URL that carries an array of
    // {q, entity} items in ?batch=. The puppeteer processes them
    // sequentially in the same tab, navigating hop-by-hop instead of
    // opening N tabs. Landing URL uses items[0] as the initial search
    // so the first hop is a normal page load.

    function makeSpotifyBatchUrl(items, action){

        if(!items.length) return null;

        const first = items[0];

        const params = new URLSearchParams();
        params.set("lastfm", "true");
        params.set("action", action);
        params.set("entity", first.entity || "track");
        params.set("batch",  JSON.stringify(items));

        return (
            "https://open.spotify.com/search/" +
            encodeURIComponent(first.q) +
            "?" + params.toString()
        );

    }



    // ---------- shared: hover menu ----------

    // Single shared menu element attached to <body>. Using position:fixed
    // avoids the recurring problem of the anchor's parent clipping the
    // popup or getting mis-positioned when Last.fm reflows the row.

    const menu = document.createElement("div");

    menu.className = "spotify-menu";

    document.body.appendChild(menu);


    let currentButton = null;

    let showTimer = null;
    let hideTimer = null;


    const HIDE_DELAY_MS = 150;
    const MENU_GAP      = 8;


    // Compact icons used inside menu items.
    const MENU_ICONS = {

        play:
            `<svg viewBox="0 0 16 16" aria-hidden="true">
                <path d="M4 2.5v11a.5.5 0 0 0 .77.42l9-5.5a.5.5 0 0 0 0-.85l-9-5.5A.5.5 0 0 0 4 2.5z"/>
            </svg>`,

        queue:
            `<svg viewBox="0 0 16 16" aria-hidden="true">
                <path d="M2 3.75A.75.75 0 0 1 2.75 3h10.5a.75.75 0 0 1 0 1.5H2.75A.75.75 0 0 1 2 3.75zm0 4A.75.75 0 0 1 2.75 7h10.5a.75.75 0 0 1 0 1.5H2.75A.75.75 0 0 1 2 7.75zm.75 3.25a.75.75 0 0 0 0 1.5h5.5a.75.75 0 0 0 0-1.5h-5.5zM12 11v-1.5h1.5V11H15v1.5h-1.5V14H12v-1.5h-1.5V11z"/>
            </svg>`,

        like:
            `<svg viewBox="0 0 16 16" aria-hidden="true">
                <path d="M8 14.25 6.83 13.2C2.68 9.61 0 7.28 0 4.5 0 2.42 1.42 1 3.5 1c1.05 0 2.09.49 2.75 1.27C6.91 1.49 7.95 1 9 1 11.08 1 12.5 2.42 12.5 4.5c0 2.78-2.68 5.11-6.83 8.71L8 14.25z"/>
            </svg>`
    };


    function positionMenu(button){

        const r = button.getBoundingClientRect();


        // Menu must already be display:block for offset dimensions to
        // be measurable.

        const mw = menu.offsetWidth;
        const mh = menu.offsetHeight;


        // Preferred: to the right of the button, top-aligned.

        let left = r.right + MENU_GAP;
        let top  = r.top;


        // If the menu would overflow the right edge, flip to the
        // left side of the button.

        if(left + mw > window.innerWidth - 8)
            left = Math.max(8, r.left - mw - MENU_GAP);


        // Keep the menu inside the viewport vertically.

        if(top + mh > window.innerHeight - 8)
            top = Math.max(8, window.innerHeight - mh - 8);


        menu.style.left = left + "px";
        menu.style.top  = top  + "px";

    }


    // Per-entity menu definition. Each item is [label, iconKey, action].
    // Labels match Spotify's own vocabulary for each entity type so
    // users know exactly what the action will do on the other side.

    const MENU_ITEMS = {
        track: [
            ["Play Song",     "play",  "play"],
            ["Queue Song",    "queue", "queue"],
            ["Like Song",     "like",  "like"]
        ],
        album: [
            ["Play Album",    "play",  "play"],
            ["Queue Album",   "queue", "queue"],
            ["Add Album",     "like",  "like"]
        ],
        artist: [
            ["Play Artist",   "play",  "play"],
            ["Queue Artist",  "queue", "queue"],
            ["Follow Artist", "like",  "like"]
        ]
    };


    function showMenu(button){

        if(hideTimer){
            clearTimeout(hideTimer);
            hideTimer = null;
        }

        currentButton = button;

        const { artist, name, entity } = button._spotify;


        menu.innerHTML = "";


        const items = MENU_ITEMS[entity] || MENU_ITEMS.track;


        items.forEach(([label, iconKey, action])=>{


            const item =
                document.createElement("div");

            item.className =
                "spotify-menu-item";

            item.innerHTML =
                MENU_ICONS[iconKey] +
                `<span>${label}</span>`;


            item.onclick=e=>{

                e.preventDefault();
                e.stopPropagation();


                openSpotify(
                    makeSpotifyUrl(
                        entity,
                        artist,
                        name,
                        action
                    )
                );


                hideMenu();

            };


            menu.appendChild(item);

        });


        menu.style.display = "block";

        // Position after making it visible so we can measure the
        // rendered size and flip if needed.

        positionMenu(button);


        // Trigger the fade-in on the next frame so the transition
        // actually runs.

        requestAnimationFrame(()=>{

            menu.classList.add("spotify-menu--shown");

        });

    }


    function scheduleShow(button){


        if(hideTimer){
            clearTimeout(hideTimer);
            hideTimer = null;
        }


        // Already showing (possibly for a different button) — re-anchor
        // immediately, no delay.

        if(menu.style.display === "block"){

            showMenu(button);

            return;

        }


        if(showTimer)
            clearTimeout(showTimer);


        // Popup slider stores `null` when the user drags to the far
        // right ("Off"); treat that as "hover menu disabled".

        const delay = getConfig().menuDelay;
        if(delay === null || delay === undefined || delay < 0) return;


        showTimer = setTimeout(()=>{

            showTimer = null;

            showMenu(button);

        }, delay);

    }


    function cancelShow(){

        if(showTimer){
            clearTimeout(showTimer);
            showTimer = null;
        }

    }


    function hideMenu(){

        menu.classList.remove("spotify-menu--shown");

        menu.style.display = "none";

        currentButton = null;

    }


    function deferHide(){

        if(hideTimer)
            clearTimeout(hideTimer);


        hideTimer = setTimeout(()=>{

            if(!menu.matches(":hover") &&
               !currentButton?.matches(":hover"))
                hideMenu();

        }, HIDE_DELAY_MS);

    }


    menu.addEventListener(
        "mouseenter",
        ()=>{
            if(hideTimer){
                clearTimeout(hideTimer);
                hideTimer = null;
            }
        }
    );

    menu.addEventListener(
        "mouseleave",
        deferHide
    );


    window.addEventListener(
        "scroll",
        ()=>{
            if(currentButton &&
               menu.style.display === "block")
                positionMenu(currentButton);
        },
        true
    );

    window.addEventListener(
        "resize",
        ()=>{
            if(currentButton &&
               menu.style.display === "block")
                positionMenu(currentButton);
        }
    );




    // ---------- button setup ----------

    function attachSpotifyBehavior(
        button,
        entity,
        artist,
        name,
        defaultAction
    ){


        button.dataset.spotifyReplaced = "true";


        button._spotify = {
            entity, artist, name
        };


        // Strip Last.fm's own hook classes so their delegated click
        // listeners (which fire on document.body in the capture phase
        // and would launch Last.fm's own player) no longer match this
        // element. We've already extracted everything we need from the
        // data-* attributes, so nuke them too — anything Last.fm's
        // player module keys off of should be gone by the time we're
        // done.

        button.classList.remove("js-playlink", "js-playlink-station");

        for (const key of Object.keys(button.dataset)) {
            if (key !== "spotifyReplaced") delete button.dataset[key];
        }


        // Last.fm's `components/link-block` module attaches a click
        // listener on every `.js-link-block` container that navigates
        // to the enclosed `link-block-target` href whenever any child
        // is clicked. That hijacks our button click (bubbles up to the
        // container, container routes to the album page).
        //
        // Neuter it on just this card: unhook the container's class
        // and disable pointer events on the invisible cover-link
        // overlay. Other links in the card (title, artist name) still
        // work as normal <a href>'s.

        const linkBlock = button.closest(".js-link-block, .link-block");

        if(linkBlock){

            linkBlock.classList.remove("js-link-block");


            const cover =
                linkBlock.querySelector(
                    ".js-link-block-cover-link, .link-block-cover-link"
                );

            if(cover){
                cover.style.pointerEvents = "none";
            }

        }


        // For the artist-page header button, keep Last.fm's native
        // "PLAY ARTIST" text alongside the Spotify icon. Everywhere
        // else, replace the whole button contents with just the icon.

        const preservedText =
            button.classList.contains("header-new-playlink")
                ? (button.textContent.trim() || "Play Artist")
                : null;

        const currentAction = getConfig().defaultAction || defaultAction;

        button.innerHTML = `
<span class="spotify-custom-button" title="">
${spotifyIcon(currentAction, entity)}
</span>${preservedText ? `<span>${preservedText}</span>` : ""}`;


        // Register the click in the capture phase so we beat any
        // still-attached document-level delegated handlers.

        button.addEventListener(
            "click",
            e => {

                e.preventDefault();
                e.stopImmediatePropagation();

                openSpotify(
                    makeSpotifyUrl(
                        entity,
                        artist,
                        name,
                        getConfig().defaultAction || defaultAction
                    )
                );

            },
            true
        );


        button.addEventListener(
            "mouseenter",
            ()=>{
                button.style.transform = "scale(1.12)";
                scheduleShow(button);
            }
        );


        button.addEventListener(
            "mouseleave",
            ()=>{
                button.style.transform = "scale(1)";
                cancelShow();
                deferHide();
            }
        );

    }




    // ---------- Last.fm targets ----------

    // Extract {entity, artist, name} from a Last.fm element using
    // layered strategies. Each strategy is tried until one returns a
    // complete tuple; if we fall past the primary path we log so we can
    // pre-empt breakage before Last.fm removes an old attribute.

    function tryStrategies(label, strategies, el){


        for(const { name, run } of strategies){


            let result;

            try {
                result = run(el);
            } catch (e) {
                log(`${label} strategy "${name}" threw:`, e);
                continue;
            }


            if(result){

                if(name !== strategies[0].name)
                    log(`${label} matched via fallback "${name}"`);

                return result;

            }

        }


        return null;

    }


    // Percent- and plus-decoded string, safe against malformed URIs.
    function decodeSeg(s){

        try {
            return decodeURIComponent(s).replace(/\+/g," ");
        } catch {
            return s.replace(/\+/g," ");
        }

    }


    // Parse the /music/{artist}[/{album|_}/{track}] path segments used
    // throughout Last.fm's URL scheme (both /music/... links and
    // /player/station/music/... station URLs).
    //
    // Last.fm reserves "+"-prefixed segments (+similar, +bookmarks,
    // +tags, +wiki, +events, +listeners, +albums, +tracks, …) for
    // meta sub-pages. They look like real path segments but have no
    // coherent Spotify equivalent, so we reject them at the parser.

    function parseMusicPath(pathish){


        const m =
            pathish.match(
                /\/music\/([^/?#]+)(?:\/([^/?#]+))?(?:\/([^/?#]+))?/
            );


        if(!m) return null;


        // Reject on raw (still-encoded) segments — Last.fm encodes
        // real spaces as "+", so we must check for the literal "+"
        // prefix before decodeSeg would turn it into " ".

        if(m[2] && m[2].startsWith("+")) return null;
        if(m[3] && m[3].startsWith("+")) return null;


        return {
            artist: decodeSeg(m[1]),
            second: m[2] ? decodeSeg(m[2]) : null,
            third:  m[3] ? decodeSeg(m[3]) : null
        };

    }



    // ----- track-style buttons (a.js-playlink) -----


    const trackStrategies = [

        // Primary: data attributes injected by Last.fm's player JS.
        {
            name: "data-track-name + data-artist-name",
            run: el => {
                const track  = el.dataset.trackName;
                const artist = el.dataset.artistName;
                if(!track || !artist) return null;
                return { entity:"track", artist, name:track };
            }
        },

        // Fallback: parse the anchor's own href.
        // Last.fm play links usually have the pattern
        //   /music/{artist}/_/{track}
        // even when the data-* attributes are absent.
        {
            name: "href /music/{artist}/_/{track}",
            run: el => {

                const href = el.getAttribute("href") || "";
                const parts = parseMusicPath(href);


                if(!parts) return null;
                if(parts.second !== "_" || !parts.third) return null;


                return {
                    entity: "track",
                    artist: parts.artist,
                    name:   parts.third
                };

            }
        },

        // Last-ditch: aria-label or title of the form "Play {track} by {artist}".
        {
            name: "aria-label ~ 'Play X by Y'",
            run: el => {

                const label =
                    el.getAttribute("aria-label") ||
                    el.getAttribute("title") ||
                    "";


                const m = label.match(/^Play\s+(.+?)\s+by\s+(.+)$/i);

                if(!m) return null;


                return {
                    entity: "track",
                    artist: m[2].trim(),
                    name:   m[1].trim()
                };

            }
        }

    ];


    function replaceTrackButtons(){


        const buttons =
            document.querySelectorAll(
                'a.js-playlink:not([data-spotify-replaced])'
            );


        buttons.forEach(button=>{


            const info =
                tryStrategies(
                    "track button",
                    trackStrategies,
                    button
                );


            if(!info) return;


            button.removeAttribute("href");
            button.removeAttribute("target");


            attachSpotifyBehavior(
                button,
                info.entity,
                info.artist,
                info.name,
                "play"
            );

        });

    }



    // ----- station-style buttons (button.js-playlink-station) -----

    // Station URLs follow:
    //   /player/station/music/{artist}                (artist radio)
    //   /player/station/music/{artist}/{album}        (album radio)
    //   /player/station/music/{artist}/_/{track}      (track radio)
    // Additional segments may appear in the future; we only inspect the
    // first three after "/music/".


    const stationStrategies = [

        // Primary: parse data-station-url.
        {
            name: "data-station-url path",
            run: el => {

                const raw = el.dataset.stationUrl || "";

                const parts = parseMusicPath(raw);

                if(!parts) return null;


                return musicPartsToInfo(parts);

            }
        },

        // Fallback: pull the same path out of a nearby link. Some
        // Last.fm pages render station buttons alongside a canonical
        // /music/... link even when data-station-url is missing.
        {
            name: "sibling /music/... anchor",
            run: el => {

                const scope =
                    el.closest(
                        "[data-track-name], [data-artist-name], article, section, li, tr"
                    ) || el.parentElement;


                if(!scope) return null;


                const a =
                    scope.querySelector('a[href*="/music/"]');


                if(!a) return null;


                const parts =
                    parseMusicPath(a.getAttribute("href") || "");


                if(!parts) return null;


                return musicPartsToInfo(parts);

            }
        }

    ];


    function musicPartsToInfo(parts){


        // Artist-only radio.
        if(!parts.second){

            return {
                entity: "artist",
                artist: parts.artist,
                name:   ""
            };

        }


        // Track — two URL shapes both use a third segment:
        //   /music/{artist}/_/{track}       Last.fm's canonical form
        //   /music/{artist}/{album}/{track} album-context (used by
        //                                   chartlist track links)
        if(parts.third){

            return {
                entity: "track",
                artist: parts.artist,
                name:   parts.third
            };

        }


        // Album (two segments).
        return {
            entity: "album",
            artist: parts.artist,
            name:   parts.second
        };

    }


    function replaceStationButtons(){



        const buttons =
            document.querySelectorAll(
                'button.js-playlink-station:not([data-spotify-replaced])'
            );


        buttons.forEach(button=>{


            // Skip the "Play all" button in the Similar Artists section
            // header — it just plays the current artist again, so it
            // duplicates the main PLAY ARTIST button. It's also hidden
            // via CSS, but skip here too so we don't attach behavior.
            if (
                button.classList.contains("inline-section-control") &&
                button
                    .closest("section")
                    ?.querySelector("ol.catalogue-overview-similar-artists")
            ) {
                return;
            }


            const info =
                tryStrategies(
                    "station button",
                    stationStrategies,
                    button
                );


            if(!info) return;


            attachSpotifyBehavior(
                button,
                info.entity,
                info.artist,
                info.name,
                "play"
            );

        });

    }



    // ----- music-card overlays -----

    // Last.fm doesn't render play buttons on many cover-art cards
    // (similar-artist grids, chart rows, recs feeds, featured tracks
    // on artist pages, etc.). We inject one per card; each config
    // below describes:
    //   card:    outer selector to enumerate (with :not(replaced) added)
    //   nameSel: link inside the card whose href gives the music path
    //   hostSel: where to append the button (null = card itself)
    //   btnCls:  which of the two overlay classes to use
    // Entity (artist/album/track) is derived from the href pattern via
    // musicPartsToInfo, so the same config works for any card type.

    const MUSIC_CARD_CONFIGS = [
        // Similar-artist grid + sidebar, /music extras, recommended lists.
        { card: ".catalogue-overview-similar-artists-item-wrap",  nameSel: ".link-block-target",                  hostSel: ".catalogue-overview-similar-artists-item-image", btnCls: "spotify-similar-artist-button" },
        { card: ".artist-similar-artists-sidebar-item-wrap",      nameSel: ".link-block-target",                  hostSel: ".artist-similar-artists-sidebar-item-image",     btnCls: "spotify-similar-artist-button" },
        { card: ".music-more-artists-item-wrap",                  nameSel: ".link-block-target",                  hostSel: ".music-more-artists-item-image",                 btnCls: "spotify-similar-artist-button" },
        { card: ".music-recommended-artists-artist",              nameSel: ".link-block-target",                  hostSel: ".music-recommended-artists-artist-avatar",       btnCls: "spotify-similar-artist-button" },

        // Featured track/album cards on an artist page ("Popular this
        // week", "Latest release", etc.). Track/album entity, cover-only
        // host, no native playlink.
        { card: ".artist-featured-items-item-wrap",               nameSel: ".link-block-target",                  hostSel: ".artist-featured-items-item-image",              btnCls: "spotify-similar-artist-button" },

        // /home/{artists|albums|...} + /music/+recommended/{...} recs-feed
        // cards. Artist / album / track variants share the same card
        // shape and injection host; entity is derived from the URL by
        // musicPartsToInfo so this one config covers them all. Skip
        // cards that already have a native .recs-feed-playlink (which
        // replaceTrackButtons or replaceStationButtons already swapped)
        // so we don't double-inject.
        { card: ".recs-feed-item:not(:has(.recs-feed-playlink))",  nameSel: ".link-block-target",                hostSel: ".recs-feed-cover-image-wrap",                    btnCls: "spotify-similar-artist-button" },

        // Chart artist rows. The .js-link-block class lives on the tr
        // only for artist rows, so it disambiguates from track/album.
        { card: "tr.globalchart-item.js-link-block",              nameSel: ".link-block-target",                  hostSel: ".globalchart-image .avatar",                     btnCls: "spotify-similar-artist-button" },
        { card: "tr.weeklychart-item.js-link-block",              nameSel: ".link-block-target",                  hostSel: ".weeklychart-image .avatar",                     btnCls: "spotify-similar-artist-button" },

        // Big featured-artist cards on /music. Button lives on the card
        // itself (top-right corner), not on any inner avatar.
        { card: ".music-featured-item.music-featured-artist",     nameSel: ".music-featured-item-heading-link",   hostSel: null,                                             btnCls: "spotify-featured-artist-button" },

        // New Releases grid on /music. Skip cards that already have
        // a native .music-releases-item-playlink (which
        // replaceStationButtons already swapped) so we don't double-
        // inject.
        { card: ".music-releases-item-wrap:not(:has(.music-releases-item-playlink))", nameSel: ".music-releases-item-name .link-block-target", hostSel: ".music-releases-item-image", btnCls: "spotify-similar-artist-button" },

        // Album-page tracklist rows. Last.fm leaves the .chartlist-play
        // cell empty on album pages; fill each empty cell with a compact
        // per-track Spotify button. requireEmptyHost skips rows that
        // already have a native play button (top-tracks lists elsewhere).
        { card: "tr.chartlist-row",                               nameSel: ".chartlist-name > a",                 hostSel: ".chartlist-play",                                btnCls: "spotify-chartlist-play-button", requireEmptyHost: true },

        // Album-page header pill area. Only inject when Last.fm didn't
        // render its own .header-new-playlink (which we would have
        // already swapped via replaceStationButtons above). On albums
        // that DO have a native play button, our swap already covers it
        // and this rule doesn't match.
        { card: "header.header-new--album:not(:has(.header-new-playlink))", nameSel: "link[itemprop='url']", hostSel: ".header-new-info-desktop .header-new-actions", btnCls: "spotify-album-header-button" },
    ];


    function replaceMusicCards(){

        for(const cfg of MUSIC_CARD_CONFIGS){

            document
                .querySelectorAll(`${cfg.card}:not([data-spotify-replaced])`)
                .forEach(card => injectMusicOverlay(card, cfg));

        }

    }


    function injectMusicOverlay(card, cfg){

        card.dataset.spotifyReplaced = "true";

        const nameLink = card.querySelector(cfg.nameSel);
        if(!nameLink) return;

        let pathname;
        try {
            pathname =
                new URL(
                    nameLink.getAttribute("href") || nameLink.href,
                    location.origin
                ).pathname;
        } catch (_) {
            return;
        }

        const parts = parseMusicPath(pathname);
        if(!parts) return;

        const info = musicPartsToInfo(parts);

        const host = cfg.hostSel ? card.querySelector(cfg.hostSel) : card;
        if(!host) return;

        // Skip if the host already has child elements (used to avoid
        // double-injecting into chartlist play cells that already have
        // a native Last.fm play button).
        if(cfg.requireEmptyHost && host.querySelector("*")) return;

        const label = info.name
            ? `Play ${info.name} by ${info.artist} on Spotify`
            : `Play ${info.artist} on Spotify`;

        const button = document.createElement("button");
        button.type = "button";
        button.className = cfg.btnCls;
        button.setAttribute("aria-label", label);
        host.appendChild(button);

        attachSpotifyBehavior(button, info.entity, info.artist, info.name, "play");

    }




    function replaceButtons(){

        replaceTrackButtons();
        replaceStationButtons();
        replaceMusicCards();
        injectNavMenu();
        injectUserPageQueueButtons();

    }



    // ---------- queue all new recommendations ----------

    // Max tracks per batch. User-configurable in the extension popup;
    // Tampermonkey (or extension pre-hydrate) falls back to the config
    // default. Hard-capped at 50 regardless so a runaway config value
    // can't overflow the URL length used to encode the batch payload.

    const QUEUE_BATCH_HARD_CAP = 50;

    function queueBatchCap(){
        const raw = getConfig().queueLimit;
        const n = Number(raw);

        if(!isFinite(n) || n < 1) return CONFIG_DEFAULTS.queueLimit || 10;
        return Math.min(Math.max(1, Math.floor(n)), QUEUE_BATCH_HARD_CAP);
    }


    // Scan a Document (either the live one or an off-screen parsed
    // page-N HTML) and return every recs-feed-item--track the user
    // hasn't already scrobbled. Last.fm renders "You have scrobbled
    // this track N times" inside the card's .context block for tracks
    // with any scrobble history; unscrobbled tracks get "Similar to
    // X, Y and Z" instead. DOM text as the filter — no API/OAuth work.
    //
    // `seen` is a shared Set the caller passes when merging across
    // pages so duplicates across page N and N+1 fold together.

    function collectRecsTracksFromDoc(doc, seen){


        const results = [];


        for(const item of doc.querySelectorAll(".recs-feed-item--track")){


            const ctx = item.querySelector(".context");

            if(ctx && /scrobbled this track/i.test(ctx.textContent || ""))
                continue;


            const titleLink =
                item.querySelector(".recs-feed-title a[href]");

            if(!titleLink) continue;


            let pathname;

            try {
                pathname =
                    new URL(
                        titleLink.getAttribute("href"),
                        location.origin
                    ).pathname;
            } catch (_) {
                continue;
            }


            const parts = parseMusicPath(pathname);
            if(!parts) continue;


            const info = musicPartsToInfo(parts);
            if(info.entity !== "track") continue;


            const q = `${info.artist} ${info.name}`;

            if(seen.has(q)) continue;

            seen.add(q);


            results.push({ q, entity:"track" });

        }


        return results;

    }


    // Locate Last.fm's classic paginator's "Next" href, if any. Present
    // on /music/+recommended/{tracks,albums,artists}?page=N; absent on
    // the masonry-layout /home and /home/{tracks,albums,artists} pages
    // where all items ship in the initial render.

    function findNextPageHref(doc){


        const link =
            doc.querySelector(
                "li.pagination-next a[href], " +
                ".pagination-next a[href], " +
                "[data-pagination-next-link] a[href]"
            );


        return link ? link.getAttribute("href") : null;

    }


    // Inject / mount the global hamburger menu next to .masthead-logo.
    // Runs on every Last.fm page. Menu items work from anywhere —
    // recommendations fetch /home/tracks when we're off a recs page,
    // neighbour queue fetches /user/{me}/neighbours first.


    const NAV_MENU_HAMBURGER_SVG = `
<svg viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg" fill="none" aria-hidden="true">
<path d="M2 5h16"  stroke="#D51007" stroke-width="2.6" stroke-linecap="round"/>
<path d="M2 10h16" stroke="#fff"    stroke-width="2.6" stroke-linecap="round"/>
<path d="M2 15h16" stroke="#1DB954" stroke-width="2.6" stroke-linecap="round"/>
</svg>`;

    const NAV_MENU_ITEM_ICONS = {

        queueRecs: `
<svg viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
<path d="M2 3.75A.75.75 0 0 1 2.75 3h10.5a.75.75 0 0 1 0 1.5H2.75A.75.75 0 0 1 2 3.75zm0 4A.75.75 0 0 1 2.75 7h10.5a.75.75 0 0 1 0 1.5H2.75A.75.75 0 0 1 2 7.75zm.75 3.25a.75.75 0 0 0 0 1.5h5.5a.75.75 0 0 0 0-1.5h-5.5zM12 11v-1.5h1.5V11H15v1.5h-1.5V14H12v-1.5h-1.5V11z"/>
</svg>`,

        // Sparkle / four-pointed star — "similar to what I love".
        queueSimilar: `
<svg viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
<path d="M8 1.2l1.6 4.2 4.2 1.6-4.2 1.6L8 12.8 6.4 8.6 2.2 7l4.2-1.6z" fill="currentColor"/>
<path d="M13 11l.5 1.5L15 13l-1.5.5L13 15l-.5-1.5L11 13l1.5-.5z" fill="currentColor" opacity=".6"/>
</svg>`,

        queueNeighbour: `
<svg viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
<circle cx="5.5" cy="5" r="2.4" fill="currentColor"/>
<path d="M1.5 13c0-2 1.8-3.4 4-3.4s4 1.4 4 3.4z" fill="currentColor"/>
<circle cx="12" cy="4.2" r="1.6" fill="currentColor" opacity=".55"/>
<path d="M9.5 9.6c0-1.3 1.1-2.2 2.5-2.2s2.5.9 2.5 2.2z" fill="currentColor" opacity=".55"/>
</svg>`,

        // Three-person cluster — "mix from multiple neighbours".
        neighbourMix: `
<svg viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
<circle cx="8" cy="4.4" r="2" fill="currentColor"/>
<path d="M4.4 12c0-1.8 1.6-3 3.6-3s3.6 1.2 3.6 3z" fill="currentColor"/>
<circle cx="2.8" cy="6.2" r="1.4" fill="currentColor" opacity=".55"/>
<circle cx="13.2" cy="6.2" r="1.4" fill="currentColor" opacity=".55"/>
<path d="M0.4 12.6c0-1.3 1.1-2.1 2.4-2.1.5 0 1 .1 1.4.3" fill="none" stroke="currentColor" stroke-width="1.2" opacity=".55" stroke-linecap="round"/>
<path d="M15.6 12.6c0-1.3-1.1-2.1-2.4-2.1-.5 0-1 .1-1.4.3" fill="none" stroke="currentColor" stroke-width="1.2" opacity=".55" stroke-linecap="round"/>
</svg>`,

    };


    const RECS_TRACKS_PAGE_PATH = "/home/tracks";


    // Cached DOM refs, populated lazily by injectNavMenu.
    let navMenuState = null;


    function injectNavMenu(){


        if(document.getElementById("spotify-nav-menu-wrap")) return;


        const logo = document.querySelector(".masthead-logo");

        if(!logo || !logo.parentElement) return;


        const wrap = document.createElement("div");

        wrap.id        = "spotify-nav-menu-wrap";
        wrap.className = "spotify-nav-menu-wrap";

        wrap.innerHTML = `
<button type="button"
        class="spotify-nav-menu-toggle"
        aria-label="Spotify tools"
        aria-haspopup="menu"
        aria-expanded="false">
${NAV_MENU_HAMBURGER_SVG}
</button>
<div class="spotify-nav-menu" role="menu" data-open="false">
<button type="button" role="menuitem" class="spotify-nav-menu-item" data-action="queue-recs">
<span class="spotify-nav-menu-icon">${NAV_MENU_ITEM_ICONS.queueRecs}</span>
<span class="spotify-nav-menu-label">Queue recommended tracks</span>
</button>
<div class="spotify-nav-menu-status" data-status-for="queue-recs" hidden></div>
<button type="button" role="menuitem" class="spotify-nav-menu-item" data-action="queue-similar">
<span class="spotify-nav-menu-icon">${NAV_MENU_ITEM_ICONS.queueSimilar}</span>
<span class="spotify-nav-menu-label">Queue similar to your top tracks</span>
</button>
<div class="spotify-nav-menu-status" data-status-for="queue-similar" hidden></div>
<button type="button" role="menuitem" class="spotify-nav-menu-item" data-action="queue-neighbour-mix">
<span class="spotify-nav-menu-icon">${NAV_MENU_ITEM_ICONS.neighbourMix}</span>
<span class="spotify-nav-menu-label">Queue random neighbour tracks</span>
</button>
<div class="spotify-nav-menu-status" data-status-for="queue-neighbour-mix" hidden></div>
<button type="button" role="menuitem" class="spotify-nav-menu-item" data-action="go-neighbour">
<span class="spotify-nav-menu-icon">${NAV_MENU_ITEM_ICONS.queueNeighbour}</span>
<span class="spotify-nav-menu-label">Go to a random neighbour</span>
</button>
<div class="spotify-nav-menu-status" data-status-for="go-neighbour" hidden></div>
</div>`;


        // Insert as a sibling immediately after .masthead-logo. The
        // wrap's CSS `margin-right:auto` overrides the parent's
        // `justify-content:space-between` so the nav cluster still
        // gets pushed to the right edge — the wrap just "steals" the
        // space-between gap and holds it, keeping itself glued to
        // the logo without repositioning anything else.
        logo.parentElement.insertBefore(wrap, logo.nextSibling);


        const toggle = wrap.querySelector(".spotify-nav-menu-toggle");
        const menu   = wrap.querySelector(".spotify-nav-menu");


        navMenuState = { wrap, toggle, menu };


        // One-shot attention pulse on first mount — draws the eye to
        // the button on page load. Removed after ~2.5s so hover and
        // expanded states aren't fighting the animation.
        toggle.classList.add("spotify-nav-menu-toggle--pulse");
        setTimeout(
            ()=> toggle.classList.remove("spotify-nav-menu-toggle--pulse"),
            2500
        );


        toggle.addEventListener("click", e => {
            e.preventDefault();
            e.stopPropagation();
            const open = menu.getAttribute("data-open") === "true";
            setNavMenuOpen(!open);
        });


        // Dismiss on outside click / Escape.
        document.addEventListener("click", e => {
            if(menu.getAttribute("data-open") !== "true") return;
            if(!wrap.contains(e.target)) setNavMenuOpen(false);
        });

        document.addEventListener("keydown", e => {
            if(e.key === "Escape" &&
               menu.getAttribute("data-open") === "true")
                setNavMenuOpen(false);
        });


        // Wire menu-item actions.
        wrap.querySelector('[data-action="queue-recs"]')
            .addEventListener("click", onMenuQueueRecs);

        wrap.querySelector('[data-action="queue-similar"]')
            .addEventListener("click", onMenuQueueSimilar);

        wrap.querySelector('[data-action="queue-neighbour-mix"]')
            .addEventListener("click", onMenuQueueNeighbourMix);

        wrap.querySelector('[data-action="go-neighbour"]')
            .addEventListener("click", onMenuGoToNeighbour);

    }


    function setNavMenuOpen(open){


        if(!navMenuState) return;

        navMenuState.menu.setAttribute("data-open", open ? "true" : "false");
        navMenuState.toggle.setAttribute("aria-expanded", open ? "true" : "false");

    }


    function setMenuItemBusy(item, busy){
        if(busy){
            item.setAttribute("aria-disabled", "true");
        } else {
            item.removeAttribute("aria-disabled");
        }
    }


    function setMenuStatus(action, text){

        const el = document.querySelector(
            `.spotify-nav-menu-status[data-status-for="${action}"]`
        );

        if(!el) return;

        if(text){
            el.hidden = false;
            el.textContent = text;
        } else {
            el.hidden = true;
            el.textContent = "";
        }

    }




    // ---------- action: Queue recommended tracks ----------

    async function onMenuQueueRecs(e){

        e.preventDefault();
        e.stopPropagation();


        const item = e.currentTarget;

        if(item.getAttribute("aria-disabled") === "true") return;

        setMenuItemBusy(item, true);
        setMenuStatus("queue-recs", "Loading your history…");


        const me = getCurrentUsername();


        let tracks = [];

        try {

            const scrobbleSet =
                me ? await getScrobbleSet(me) : new Set();

            setMenuStatus("queue-recs", "Loading recommendations…");

            tracks = await collectMergedRecs(queueBatchCap(), scrobbleSet);

        } catch (err) {

            log("Queue recs failed:", err);

        }


        if(!tracks.length){
            setMenuStatus("queue-recs", "No new tracks found");
            setTimeout(()=> setMenuStatus("queue-recs", null), 2500);
            setMenuItemBusy(item, false);
            return;
        }


        const url = makeSpotifyBatchUrl(tracks, "queue");

        setMenuStatus(
            "queue-recs",
            `Queuing ${tracks.length} track${tracks.length === 1 ? "" : "s"}…`
        );

        log(`Queuing ${tracks.length} recommended track(s) to Spotify`);

        openSpotify(url);


        setTimeout(()=>{
            setMenuStatus("queue-recs", null);
            setMenuItemBusy(item, false);
            setNavMenuOpen(false);
        }, 1800);

    }


    // ---------- action: Queue similar to your top tracks ----------

    async function onMenuQueueSimilar(e){

        e.preventDefault();
        e.stopPropagation();


        const item = e.currentTarget;

        if(item.getAttribute("aria-disabled") === "true") return;


        const me = getCurrentUsername();

        if(!me){
            setMenuItemBusy(item, true);
            setMenuStatus("queue-similar", "Couldn't determine your username");
            setTimeout(()=>{
                setMenuStatus("queue-similar", null);
                setMenuItemBusy(item, false);
            }, 2500);
            return;
        }


        setMenuItemBusy(item, true);
        setMenuStatus("queue-similar", "Loading your history…");


        let tracks = [];

        try {

            const scrobbleSet = await getScrobbleSet(me);

            setMenuStatus(
                "queue-similar",
                "Finding tracks similar to your top…"
            );

            tracks = await collectSimilarToTopTracks(
                queueBatchCap(), scrobbleSet, me
            );

        } catch (err) {

            log("Queue similar failed:", err);

        }


        if(!tracks.length){
            setMenuStatus("queue-similar", "No similar tracks found");
            setTimeout(()=> setMenuStatus("queue-similar", null), 2500);
            setMenuItemBusy(item, false);
            return;
        }


        const url = makeSpotifyBatchUrl(tracks, "queue");

        setMenuStatus(
            "queue-similar",
            `Queuing ${tracks.length} track${tracks.length === 1 ? "" : "s"}…`
        );

        log(`Queuing ${tracks.length} similar track(s) to Spotify`);

        openSpotify(url);


        setTimeout(()=>{
            setMenuStatus("queue-similar", null);
            setMenuItemBusy(item, false);
            setNavMenuOpen(false);
        }, 1800);

    }


    // ---------- action: Queue random neighbour tracks (mix) ----------

    async function onMenuQueueNeighbourMix(e){

        e.preventDefault();
        e.stopPropagation();


        const item = e.currentTarget;

        if(item.getAttribute("aria-disabled") === "true") return;


        const me = getCurrentUsername();

        if(!me){
            setMenuItemBusy(item, true);
            setMenuStatus(
                "queue-neighbour-mix",
                "Couldn't determine your username"
            );
            setTimeout(()=>{
                setMenuStatus("queue-neighbour-mix", null);
                setMenuItemBusy(item, false);
            }, 2500);
            return;
        }


        setMenuItemBusy(item, true);
        setMenuStatus("queue-neighbour-mix", "Loading your history…");


        let tracks = [];
        let neighbours = [];

        try {

            const scrobbleSet = await getScrobbleSet(me);

            setMenuStatus(
                "queue-neighbour-mix",
                "Loading neighbours' tracks…"
            );

            const result = await collectNeighbourMix(
                queueBatchCap(), scrobbleSet, me
            );

            tracks     = result.tracks;
            neighbours = result.neighbours;

        } catch (err) {

            log("Queue neighbour mix failed:", err);

        }


        if(!tracks.length){
            setMenuStatus(
                "queue-neighbour-mix",
                neighbours.length
                    ? "No new tracks from your neighbours"
                    : "No neighbours found"
            );
            setTimeout(
                ()=> setMenuStatus("queue-neighbour-mix", null),
                2500
            );
            setMenuItemBusy(item, false);
            return;
        }


        const url = makeSpotifyBatchUrl(tracks, "queue");

        const namesJoined = neighbours.slice(0, 3).join(", ");

        setMenuStatus(
            "queue-neighbour-mix",
            `Queuing ${tracks.length} from ${namesJoined}…`
        );

        log(
            `Queuing ${tracks.length} neighbour-mix track(s) from ${namesJoined}`
        );

        openSpotify(url);


        setTimeout(()=>{
            setMenuStatus("queue-neighbour-mix", null);
            setMenuItemBusy(item, false);
            setNavMenuOpen(false);
        }, 2000);

    }


    // ---------- action: Go to a random neighbour ----------

    async function onMenuGoToNeighbour(e){

        e.preventDefault();
        e.stopPropagation();


        const item = e.currentTarget;

        if(item.getAttribute("aria-disabled") === "true") return;

        setMenuItemBusy(item, true);
        setMenuStatus("go-neighbour", "Finding a neighbour…");


        const me = getCurrentUsername();

        if(!me){
            setMenuStatus("go-neighbour", "Couldn't determine your username");
            setTimeout(()=> setMenuStatus("go-neighbour", null), 2500);
            setMenuItemBusy(item, false);
            return;
        }


        let neighbour;

        try {

            const neighboursDoc =
                await fetchDoc(`/user/${encodeURIComponent(me)}/neighbours`);

            if(!neighboursDoc)
                throw new Error("neighbours page unreachable");


            const neighbours =
                extractNeighbourUsernames(neighboursDoc, me);

            if(!neighbours.length)
                throw new Error("no neighbours found");


            neighbour = neighbours[
                Math.floor(Math.random() * neighbours.length)
            ];


        } catch (err) {

            log("Go to neighbour failed:", err);

        }


        if(!neighbour){
            setMenuStatus("go-neighbour", "No neighbours found");
            setTimeout(()=> setMenuStatus("go-neighbour", null), 2500);
            setMenuItemBusy(item, false);
            return;
        }


        setMenuStatus("go-neighbour", `Going to ${neighbour}…`);

        log(`Navigating to neighbour "${neighbour}"`);

        // Same-tab navigation into the neighbour's profile. From there
        // the injected "Queue top tracks" / "Queue recent tracks"
        // pills on the profile header do the actual queueing.
        window.location.href = `/user/${encodeURIComponent(neighbour)}`;

    }




    // ---------- user-page pill: Queue top / recent tracks ----------

    const USER_QUEUE_ICONS = {

        // Ascending bar chart — "top tracks".
        top: `
<svg viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
<rect x="1.5" y="10" width="3" height="4.5" rx="0.6"/>
<rect x="6.5" y="6"  width="3" height="8.5" rx="0.6"/>
<rect x="11.5" y="2" width="3" height="12.5" rx="0.6"/>
</svg>`,

        // Clock — "recent tracks".
        recent: `
<svg viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" fill="none">
<circle cx="8" cy="8" r="6.2" stroke="currentColor" stroke-width="1.4"/>
<path d="M8 4.5v4l2.8 1.6" stroke="currentColor" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"/>
</svg>`,

    };


    function injectUserPageQueueButtons(){


        // Only meaningful on user pages. The section headers we look
        // for are only rendered under /user/{name}/*.

        if(!/^\/user\/[^\/?#]+/.test(location.pathname)) return;


        // Recent Tracks section — h2 anchor points at /user/{name}/library.
        injectSectionQueuePill({
            headerSel: "#recent-tracks-section h2, section:has(> h2 > a[href*='/library']) > h2",
            iconSvg:   USER_QUEUE_ICONS.recent,
            label:     "Queue recent",
            urlFilter: href => /\/library\/?($|\?|#)/.test(href),
        });


        // Top Tracks section — h2 anchor points at /user/{name}/library/tracks.
        injectSectionQueuePill({
            headerSel: "#top-tracks h2",
            iconSvg:   USER_QUEUE_ICONS.top,
            label:     "Queue top",
            urlFilter: href => /\/library\/tracks/.test(href),
        });

    }


    // Attach a compact "Queue …" pill to a section's <h2>. The pill's
    // target URL is pulled from the section header's own <a> so the
    // fetch reflects whatever time-range filter Last.fm is currently
    // showing (Top Tracks defaults to LAST_7_DAYS; the anchor href
    // carries that ?date_preset param).

    function injectSectionQueuePill({ headerSel, iconSvg, label, urlFilter }){


        const header = document.querySelector(headerSel);

        if(!header) return;

        if(header.querySelector(".spotify-user-queue-pill")) return;


        const anchor = header.querySelector("a[href]");

        if(!anchor) return;


        let href = anchor.getAttribute("href");

        if(urlFilter && !urlFilter(href)) return;


        const pill = document.createElement("button");

        pill.type      = "button";
        pill.className = "spotify-user-queue-button spotify-user-queue-pill";

        pill.innerHTML = `
<span class="spotify-user-queue-icon">${iconSvg}</span>
<span>${label}</span>`;


        pill.addEventListener(
            "click",
            e => onClickQueueFromSection(e, href)
        );


        header.appendChild(pill);

    }


    async function onClickQueueFromSection(e, href){

        e.preventDefault();
        e.stopPropagation();


        const btn = e.currentTarget;

        if(btn.getAttribute("aria-disabled") === "true") return;


        const label = btn.querySelector("span:not(.spotify-user-queue-icon)");
        const originalText = label ? label.textContent : "";


        btn.setAttribute("aria-disabled", "true");
        if(label) label.textContent = "Loading…";


        let tracks = [];

        try {
            const doc = await fetchDoc(href);
            if(doc)
                tracks = extractChartlistTracks(doc).slice(0, queueBatchCap());
        } catch (err) {
            log("Queue from section failed:", err);
        }


        if(!tracks.length){
            if(label) label.textContent = "No tracks found";
            setTimeout(()=>{
                if(label) label.textContent = originalText;
                btn.removeAttribute("aria-disabled");
            }, 2000);
            return;
        }


        const url = makeSpotifyBatchUrl(tracks, "queue");

        if(label) label.textContent = `Queuing ${tracks.length}…`;

        log(`Queuing ${tracks.length} track(s) from ${href}`);

        openSpotify(url);


        setTimeout(()=>{
            if(label) label.textContent = originalText;
            btn.removeAttribute("aria-disabled");
        }, 2000);

    }




    // ---------- shared helpers for menu actions ----------

    async function fetchDoc(pathOrHref){

        try {

            const res = await fetch(
                new URL(pathOrHref, location.origin).toString(),
                { credentials:"same-origin" }
            );

            if(!res.ok) return null;

            const html = await res.text();

            return new DOMParser().parseFromString(html, "text/html");

        } catch (_) {
            return null;
        }

    }


    // Pull neighbour usernames out of /user/{me}/neighbours. Last.fm
    // renders neighbour cards with links to /user/{name}; filter to
    // just that pattern and exclude self.

    function extractNeighbourUsernames(doc, selfUsername){


        const usernames = new Set();


        for(const a of doc.querySelectorAll('a[href*="/user/"]')){


            let name;

            try {
                const path =
                    new URL(a.getAttribute("href"), location.origin).pathname;

                const m = path.match(/^\/user\/([^\/?#]+)\/?$/);

                if(!m) continue;

                name = decodeSeg(m[1]);

            } catch (_) {
                continue;
            }


            if(!name || name === selfUsername) continue;

            // Reject Last.fm meta segments (+bookmarks etc.) — the
            // pattern above already excludes trailing paths, but
            // usernames don't start with "+".
            if(name.startsWith("+")) continue;

            usernames.add(name);

        }


        return [...usernames];

    }


    // Pull artist+track pairs from a chartlist (used on user library
    // pages, album pages, artist top-tracks lists, weekly charts).

    function extractChartlistTracks(doc){


        const results = [];
        const seen    = new Set();


        for(const row of doc.querySelectorAll("tr.chartlist-row, .chartlist-row")){


            const nameLink =
                row.querySelector(".chartlist-name a[href*='/music/']");

            if(!nameLink) continue;


            let pathname;

            try {
                pathname =
                    new URL(
                        nameLink.getAttribute("href"),
                        location.origin
                    ).pathname;
            } catch (_) {
                continue;
            }


            const parts = parseMusicPath(pathname);
            if(!parts) continue;


            const info = musicPartsToInfo(parts);
            if(info.entity !== "track") continue;


            const q = `${info.artist} ${info.name}`;

            if(seen.has(q)) continue;

            seen.add(q);


            results.push({ q, entity:"track", artist:info.artist, name:info.name });

        }


        return results;

    }


    function getCurrentUsername(){


        // Multiple hooks — masthead dropdown link is most reliable
        // when logged in, avatar link works on the mobile layout.

        const link =
            document.querySelector(
                '.auth-dropdown-profile[href*="/user/"], ' +
                '.auth-avatar-mobile[href*="/user/"], ' +
                '.masthead-user-menu-toggle[href*="/user/"]'
            );


        if(!link) return null;


        try {

            const path =
                new URL(link.getAttribute("href"), location.origin).pathname;

            const m = path.match(/^\/user\/([^\/?#]+)/);

            return m ? decodeSeg(m[1]) : null;

        } catch (_) {
            return null;
        }

    }


    // Encode a decoded artist/track segment back into Last.fm's URL
    // shape. encodeURIComponent produces "%20" for spaces; Last.fm's
    // canonical URLs use "+" (see any anchor href on the site).

    function encodeSeg(s){
        return encodeURIComponent(s).replace(/%20/g, "+");
    }


    // Pull tracks from a paginated /music/+recommended/tracks page.
    // Different DOM shape from the /home/tracks masonry (this one uses
    // .recommended-tracks-item-wrap) and no scrobble metadata in-DOM,
    // so the scrobble filter has to come from a separate library scan.

    function collectRecommendedItemsFromDoc(doc, seen){


        const results = [];


        for(const item of doc.querySelectorAll(".recommended-tracks-item-wrap")){


            const nameLink =
                item.querySelector(".recommended-tracks-item-name a[href*='/music/']");

            if(!nameLink) continue;


            let pathname;

            try {
                pathname =
                    new URL(
                        nameLink.getAttribute("href"),
                        location.origin
                    ).pathname;
            } catch (_) {
                continue;
            }


            const parts = parseMusicPath(pathname);
            if(!parts) continue;


            const info = musicPartsToInfo(parts);
            if(info.entity !== "track") continue;


            const q = `${info.artist} ${info.name}`;

            if(seen.has(q)) continue;

            seen.add(q);


            results.push({ q, entity:"track", artist:info.artist, name:info.name });

        }


        return results;

    }



    // ---------- scrobble-set filter ----------

    // Bounded snapshot of the user's scrobble history used to filter
    // rec-source results down to "new to me" tracks. Fetches page-1..3
    // of their all-time-top library and their recent scrobble history
    // — first is where duplicates are most likely (top-scrobbled),
    // second catches recently-listened but not necessarily top ones.
    // Long-tail one-off scrobbles from years ago will slip through;
    // that's an accepted trade-off for keeping this cheap.

    const SCROBBLE_SET_TTL_MS = 120000;
    const SCROBBLE_SET_PAGES  = 3;

    let scrobbleSetCache = null;


    async function getScrobbleSet(username){


        if(scrobbleSetCache &&
           scrobbleSetCache.username === username &&
           Date.now() - scrobbleSetCache.at < SCROBBLE_SET_TTL_MS){

            return scrobbleSetCache.set;

        }


        const set = new Set();

        const bases = [
            `/user/${encodeURIComponent(username)}/library/tracks`,
            `/user/${encodeURIComponent(username)}/library`,
        ];


        for(const base of bases){

            for(let page = 1; page <= SCROBBLE_SET_PAGES; page++){

                const url = page === 1 ? base : `${base}?page=${page}`;

                const doc = await fetchDoc(url);
                if(!doc) break;

                const tracks = extractChartlistTracks(doc);
                if(!tracks.length) break;

                for(const t of tracks) set.add(t.q.toLowerCase());

            }

        }


        scrobbleSetCache = { username, set, at:Date.now() };

        return set;

    }


    function filterUnscrobbled(tracks, scrobbleSet){
        return tracks.filter(t => !scrobbleSet.has(t.q.toLowerCase()));
    }



    // ---------- merged recs (both surfaces) ----------

    // Union of /home/tracks (masonry, has in-DOM scrobble text) and
    // /music/+recommended/tracks (paginated, no scrobble metadata).
    // Both go through the shared scrobble-set filter so overlap and
    // long-tail scrobbles are stripped.

    async function collectMergedRecs(cap, scrobbleSet){


        const seen      = new Set();
        const collected = [];


        // Source A: /home/tracks (or live doc if we're on it)
        const startDoc =
            document.querySelector(".recs-feed-item--track")
                ? document
                : await fetchDoc(RECS_TRACKS_PAGE_PATH);

        if(startDoc){
            const items = filterUnscrobbled(
                collectRecsTracksFromDoc(startDoc, seen),
                scrobbleSet
            );
            collected.push(...items);
        }

        if(collected.length >= cap)
            return collected.slice(0, cap);


        // Source B: /music/+recommended/tracks, walk pagination.
        let path = "/music/+recommended/tracks";

        while(path && collected.length < cap){

            const doc = await fetchDoc(path);
            if(!doc) break;

            const items = filterUnscrobbled(
                collectRecommendedItemsFromDoc(doc, seen),
                scrobbleSet
            );
            collected.push(...items);

            path = findNextPageHref(doc);

        }


        return collected.slice(0, cap);

    }



    // ---------- similar to top tracks ----------

    // Grab the user's top ~10 tracks, then in parallel fetch each
    // track's page and extract its "Similar Tracks" section (embedded
    // on the track page under .track-similar-tracks-item-wrap). Filters
    // out both the seeds themselves and anything already in the
    // scrobble set.

    const SIMILAR_SEEDS = 10;


    // Extract tracks from the "Similar Tracks" grid embedded on a
    // track page. Same conceptual shape as the /music/+recommended
    // and /home/tracks extractors — different item class.

    function collectTrackSimilarItemsFromDoc(doc, seen){


        const results = [];


        for(const item of doc.querySelectorAll(".track-similar-tracks-item-wrap")){


            const nameLink =
                item.querySelector(".track-similar-tracks-item-name a[href*='/music/']");

            if(!nameLink) continue;


            let pathname;

            try {
                pathname =
                    new URL(
                        nameLink.getAttribute("href"),
                        location.origin
                    ).pathname;
            } catch (_) {
                continue;
            }


            const parts = parseMusicPath(pathname);
            if(!parts) continue;


            const info = musicPartsToInfo(parts);
            if(info.entity !== "track") continue;


            const q = `${info.artist} ${info.name}`;

            if(seen.has(q)) continue;

            seen.add(q);


            results.push({ q, entity:"track", artist:info.artist, name:info.name });

        }


        return results;

    }


    async function collectSimilarToTopTracks(cap, scrobbleSet, username){


        const seedDoc =
            await fetchDoc(`/user/${encodeURIComponent(username)}/library/tracks`);

        if(!seedDoc) return [];


        const seeds =
            extractChartlistTracks(seedDoc).slice(0, SIMILAR_SEEDS);

        if(!seeds.length) return [];


        // Seed q-strings so similar-results that just re-surface a
        // seed are excluded.
        const seen = new Set(seeds.map(s => s.q));


        // Parallel fetch — 10 hops in serial would be ~5s, in parallel
        // ~500ms. Same-origin so no CORS. The track page itself hosts
        // the "Similar Tracks" section (typically 6 items).
        const similarDocs =
            await Promise.all(
                seeds.map(s =>
                    fetchDoc(
                        `/music/${encodeSeg(s.artist)}/_/${encodeSeg(s.name)}`
                    )
                )
            );


        const collected = [];


        for(const doc of similarDocs){

            if(collected.length >= cap) break;
            if(!doc) continue;

            const rows = collectTrackSimilarItemsFromDoc(doc, seen);

            for(const t of rows){
                if(collected.length >= cap) break;
                if(scrobbleSet.has(t.q.toLowerCase())) continue;
                collected.push({ q:t.q, entity:t.entity });
            }

        }


        return collected;

    }



    // ---------- neighbour mix ----------

    // Pick a few top neighbours, pull each one's top + recent tracks
    // in parallel, shuffle each list, and round-robin merge into a
    // "mix" that's less dominated by any single neighbour's library.

    const NEIGHBOUR_MIX_COUNT = 3;

    function shuffleInPlace(arr){
        for(let i = arr.length - 1; i > 0; i--){
            const j = Math.floor(Math.random() * (i + 1));
            [arr[i], arr[j]] = [arr[j], arr[i]];
        }
        return arr;
    }


    async function collectNeighbourMix(cap, scrobbleSet, username){


        const neighboursDoc =
            await fetchDoc(`/user/${encodeURIComponent(username)}/neighbours`);

        if(!neighboursDoc) return { tracks:[], neighbours:[] };


        const neighbours =
            extractNeighbourUsernames(neighboursDoc, username);

        if(!neighbours.length) return { tracks:[], neighbours:[] };


        const picked = neighbours.slice(0, NEIGHBOUR_MIX_COUNT);


        // For each picked neighbour, fetch top + recent in parallel.
        const perNeighbour =
            await Promise.all(
                picked.map(async n => {

                    const [topDoc, recentDoc] = await Promise.all([
                        fetchDoc(`/user/${encodeURIComponent(n)}/library/tracks`),
                        fetchDoc(`/user/${encodeURIComponent(n)}/library`),
                    ]);


                    const combined = [];

                    if(topDoc)    combined.push(...extractChartlistTracks(topDoc));
                    if(recentDoc) combined.push(...extractChartlistTracks(recentDoc));


                    return shuffleInPlace(combined);

                })
            );


        // Round-robin merge for a balanced mix.
        const seen      = new Set();
        const collected = [];


        while(collected.length < cap){

            let advanced = false;

            for(const list of perNeighbour){

                if(collected.length >= cap) break;

                while(list.length){

                    const t = list.shift();

                    if(seen.has(t.q)) continue;
                    if(scrobbleSet.has(t.q.toLowerCase())) continue;

                    seen.add(t.q);
                    collected.push({ q:t.q, entity:t.entity });
                    advanced = true;
                    break;

                }

            }

            if(!advanced) break;

        }


        return { tracks:collected, neighbours:picked };

    }




    // ---------- run + observe ----------

    replaceButtons();


    // Debounced observer: Last.fm re-renders track lists on route changes
    // and infinite-scroll; without debouncing this would run dozens of
    // times per second.

    let scheduled = false;

    function scheduleReplace(){

        if(scheduled) return;
        scheduled = true;


        requestAnimationFrame(()=>{
            scheduled = false;
            replaceButtons();
        });

    }


    new MutationObserver(scheduleReplace)
        .observe(
            document.body,
            {
                childList:true,
                subtree:true
            }
        );


    // Live-refresh injected icons when the extension popup changes the
    // default click action or the entity-badges toggle. The bridge
    // dispatches this CustomEvent on storage change; under Tampermonkey
    // it never fires and icons reflect the CONFIG_DEFAULTS at page load.

    window.addEventListener("__lfs-config-changed", e => {

        if (!e.detail) return;
        if (!e.detail.defaultAction && !e.detail.entityBadges) return;

        const action = getConfig().defaultAction || "play";

        document
            .querySelectorAll("[data-spotify-replaced] .spotify-custom-button")
            .forEach(span => {
                const button = span.closest("[data-spotify-replaced]");
                const entity = button?._spotify?.entity || null;
                span.innerHTML = spotifyIcon(action, entity);
            });

    });


    // Explicit hook for SPA-style navigations. The observer above
    // already catches most re-renders, but wrapping history.pushState
    // guarantees we rescan the moment the URL changes even if the new
    // DOM commit is small.

    ["pushState","replaceState"].forEach(k=>{

        const orig = history[k];

        history[k] = function(){

            const r = orig.apply(this, arguments);

            scheduleReplace();

            return r;

        };

    });


    window.addEventListener("popstate", scheduleReplace);

})();
