#!/usr/bin/env bash
#
# Builds the two userscripts by concatenating their module files.
#
# Each module directory under src/ has:
#   HEADER.txt   Tampermonkey/UserScript metadata block, prepended verbatim.
#   build.json   { output, header, files: [ordered list of .js modules] }
#   NN-*.js      Individual module files. Concatenated in the order listed.
#
# The concatenated body is wrapped in a single top-level IIFE with
# `'use strict'`. All modules share the IIFE's scope — no imports/exports.
# Ordering in build.json is significant only for value initialization
# (`const X = ...` before first use); function declarations hoist across
# module boundaries.
#
# Generated `.user.js` files sit at the repo root so:
#   1. Tampermonkey users install them from raw GitHub URLs, unchanged.
#   2. scripts/sync-extension.sh continues to copy them into extension/.

set -euo pipefail

repo_root="$(cd "$(dirname "$0")/.." && pwd)"
src_root="$repo_root/src"


# Extract a top-level string value from a JSON file. Simple grep-based
# parser to avoid a jq dependency. Handles "key": "value" pairs.
json_string() {
    local file="$1" key="$2"
    grep -oE "\"${key}\"[[:space:]]*:[[:space:]]*\"[^\"]*\"" "$file" \
        | head -1 \
        | sed -E "s/.*\"${key}\"[[:space:]]*:[[:space:]]*\"([^\"]*)\".*/\1/"
}


# Extract the ordered list of filenames from the "files" array of a
# build.json. Line-oriented so array entries must be one per line.
json_array_files() {
    local file="$1"
    awk '/"files"[[:space:]]*:/{inarr=1;next} inarr && /\]/{inarr=0;next} inarr' "$file" \
        | grep -oE '"[^"]+"' \
        | tr -d '"'
}


build_module() {
    local module_dir="$1"
    local dir="$src_root/$module_dir"
    local manifest="$dir/build.json"

    local output
    output="$(json_string "$manifest" output)"
    local header_file
    header_file="$(json_string "$manifest" header)"

    local out_path="$repo_root/$output"

    mkdir -p "$(dirname "$out_path")"

    # Header + auto-generated banner + IIFE opener.
    {
        cat "$dir/$header_file"
        printf '\n// AUTO-GENERATED from src/%s/. Do not edit this file directly.\n' "$module_dir"
        printf '// Edit the module files under src/%s/ and re-run scripts/build.sh.\n\n' "$module_dir"
        printf '(function () {\n'
        printf "    'use strict';\n\n"

        # Body — each module file separated by a blank line, mirroring
        # the original hand-authored userscript's section spacing.
        local first=1
        while IFS= read -r file; do
            if [[ $first -eq 0 ]]; then printf '\n'; fi
            cat "$dir/$file"
            first=0
        done < <(json_array_files "$manifest")

        # IIFE closer.
        printf '})();\n'
    } > "$out_path"

    local n_modules line_count
    n_modules=$(json_array_files "$manifest" | wc -l | tr -d ' ')
    line_count=$(wc -l < "$out_path" | tr -d ' ')
    printf 'Built %s — %s modules, %s lines\n' \
        "$output" "$n_modules" "$line_count"
}


build_module lastfm-inject
build_module spotify-puppeteer
